parameters: 
  - name: stageid
    type: string
  - name: resourceGroupName
    type: string
  - name: location
    type: string
  - name: part
    type: string
  - name: environmentName
    type: string
  - name: bicepTemplateFile
    type: string
  - name: bicepParametersFile
    type: string
  - name: serviceConnection
    type: string

stages: 
  - stage: "${{ parameters.stageId }}"
    displayName: "Deploying [${{parameters.part}}]"
    #dependsOn: ${{ parameters.dependson }}
    jobs:
      - deployment: Deploy
        displayName: "Deploying to [${{upper(parameters.environmentName)}}] Environment" 
        environment: ${{parameters.environmentName}}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                
                
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: ${{parameters.serviceConnection}}
                    scriptType: 'ps'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      # Deploy the Bicep template to the specified resource group
                      az deployment group create --resource-group ${{ parameters.resourceGroupName }} --template-file ${{ parameters.bicepTemplateFile }} --parameters ${{ parameters.bicepParametersFile }}



