# below is stated how the pipeline will be triggered(when a change will happen in main branch)
trigger:
  - main

# in azure devops there is a variable group with the following name which contains variables that will be used for the deployment in each environment
variables:
  - group: group1

# Define runtime parameters
#parameters:
#  - name: integrationRuntimeKey
#    displayName: "Integration Runtime Key"
#    type: string
#    default: ""
    
# the following are parameters that can be used anywhere in this yml code
  
#  - name: notebooksPath
#    value: "DLT_pipeline"
#  - name: location
#    value: "eastus"

# compute power that Microsoft provides to execute a CI/CD pipeline in devops (https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
pool: 
  name: vziog
  demands: agent.name -equals ZIOGOU-NB


# below are defined the stages
stages:

#stage 1: deployment of resources that are managed from resource manager part1
  - template: templates/run-bicep.yml
    parameters:
      stageid: "Deploy_part1_to_Dev_Environment"
      part: 'part1'
      # this is the environment of devops where you can manage deployments, view resource status, etc
      environmentName: $(dev-environment-name)
      resourceGroupName: $(dev-resource-group-name)
      location: $(location)
      # this is the service connecion to the resource group where dev databricks workspace is (recommended type is service principal automatic through resource manager)
      serviceConnection: $(dev-service-connection-name)
      bicepTemplateFile: "Pipeline/ARM/main_part1.bicep"
      bicepParametersFile: "Pipeline/ARM/main_part1.bicepparam"

#stage 2: configure integration runtime
#  - stage: "Configure_integartion_runtime1"
#    displayName: "Configure Integration Runtime of Data Factory1"
#    jobs:
#    - deployment: Deploy
#      displayName: "Configure Integration Runtime of Data Factory2"
#      environment: 'IntegrationRuntimeApproval'
#      
#      strategy:
#        runOnce:
#          deploy:
#            steps:
#              - checkout: self
#
#              # Azure CLI Task to run PowerShell script
#              - task: AzureCLI@2
#                inputs:
#                  azureSubscription: $(dev-service-connection-name)  # Service Connection Name
#                  scriptType: 'ps'  # Use PowerShell
#                  scriptLocation: 'inlineScript'  # Inline script
#                  inlineScript: |
#                    cd $(Build.SourcesDirectory)/Pipeline/ARM
#                    .\RegisterIntegrationRuntime2.ps1 -GatewayKey $(integrationRuntimeKey) -IsRegisterOnRemoteMachine false

#stage 2: deployment of resources that are managed from resource manager part2
  - template: templates/run-bicep.yml
    parameters:
      stageid: "Deploy_part2_to_Dev_Environment"
      part: 'part2'
      # this is the environment of devops where you can manage deployments, view resource status, etc
      environmentName: 'part2withApproval'
      resourceGroupName: $(dev-resource-group-name)
      location: $(location)
      # this is the service connecion to the resource group where dev databricks workspace is (recommended type is service principal automatic through resource manager)
      serviceConnection: $(dev-service-connection-name)
      bicepTemplateFile: "Pipeline/ARM/main_part2.bicep"
      bicepParametersFile: "Pipeline/ARM/main_part2.bicepparam"
                    

#stage 3: "configure integration runtime"
  - stage: "Deploy_managed_resource_group"
    displayName: "Deploy on Sub level"
    jobs:
      - deployment: Deploy
        displayName: "kati"
        environment: $(dev-environment-name)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                # Azure CLI Task to run PowerShell script
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: $(dev-service-connection-name)  # Service Connection Name
                    scriptType: 'ps'  # Use PowerShell
                    scriptLocation: 'inlineScript'  # Inline script
                    inlineScript: |  
                      az deployment sub create --location 'eastus' --template-file "Pipeline/ARM/ManagedResourceGroup.bicep"

#stage 4: configure integration runtime
  - stage: "Deploy_databricks"
    displayName: "Deploy databricks on dev"
    jobs:
    - deployment: Deploy
      displayName: "Deploy databricks on dev 2"
      environment: $(dev-environment-name)
      
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self

              # Azure CLI Task to run PowerShell script
              - task: AzureCLI@2
                inputs:
                  azureSubscription: $(dev-service-connection-name)  # Service Connection Name
                  scriptType: 'ps'  # Use PowerShell
                  scriptLocation: 'inlineScript'  # Inline script
                  inlineScript: |
                    az deployment group create --resource-group 'dp203' --template-file <Pipeline/ARM/Databricks.bicep>